version: 2.1


orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      # Using CircleCI's OpenJDK image which includes Maven
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      # Checkout the code
      - checkout

      # Set up Maven cache to avoid downloading dependencies every time
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      # Run Maven to download dependencies
      - run:
          name: Install Maven dependencies
          command: mvn dependency:go-offline -B

      # Save Maven dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      # Run Maven tests
      - run:
          name: Run tests
          command: mvn test

      # Optionally: Store test results for better visibility in CircleCI
      - store_test_results:
          path: target/surefire-reports/


workflows:
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
      - build
      - codecov/upload:
          requires:
            - build

