version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1


jobs:
  build:
    docker:
      # Using CircleCI's OpenJDK image which includes Maven
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      # Checkout the code
      - checkout

      # Set up Maven cache to avoid downloading dependencies every time
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      # Run Maven to download dependencies
      - run:
          name: Install Maven dependencies
          command: mvn dependency:go-offline -B

      # Save Maven dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}


      - run:
          name: Build and run tests with coverage
          command: mvn clean verify


      - run:
          name: Generate coverage report
          command: mvn jacoco:report
      - codecov/upload


      - run:
          name: Generate Javadoc
          command: |
            mvn javadoc:javadoc


      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

      - run:
          name: Publish Javadoc to GitHub Pages
          command: |-
            git config --global user.email "nassim.ezzaamari@alumni.univ-avignon.fr"
            git config --global user.name "nassimezzaamari"
            
            mkdir -p target/site/javadoc
            
            cp -r target/site/apidocs/* target/site/javadoc/
            
            git checkout --orphan gh-pages
            git rm -rf .
            
            cp -r target/site/javadoc/. .
            git add .

            git commit -m "javadoc ajout"
            git push --force --set-upstream origin gh-pages
              

      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

      # Optionally: Store test results for better visibility in CircleCI
      - store_test_results:
          path: target/surefire-reports/



workflows:
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
