version: 2.1

jobs:
  build:
    docker:
      # Using CircleCI's OpenJDK image which includes Maven
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      # Checkout the code
      - checkout

      # Set up Maven cache to avoid downloading dependencies every time
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      # Run Maven to download dependencies
      - run:
          name: Install Maven dependencies
          command: mvn dependency:go-offline -B

      # Save Maven dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}


      - run:
          name: Build and run tests with coverage
          command: mvn clean verify

      - run:
          name: Generate coverage report
          command: mvn jacoco:report


      # Optionally: Store test results for better visibility in CircleCI
      - store_test_results:
          path: target/surefire-reports/


      - codecov/upload

workflows:
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
