version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Install Maven dependencies
          command: mvn dependency:go-offline -B

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      - run:
          name: Build and run tests with coverage
          command: mvn clean verify

      - run:
          name: Run checkstyle
          command: mvn checkstyle:check

      - run:
          name: Generate coverage report
          command: mvn jacoco:report

      # Génération de la Javadoc
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

      # Configuration de Git pour GitHub Pages
      - run:
          name: Configure Git user
          command: |
            git config user.email "ci-build@circleci.com"
            git config user.name "CI Build"

      # Publication de la Javadoc sur GitHub Pages
      - run:
          name: Publish Javadoc to GitHub Pages
          command: |
            git checkout --orphan gh-pages
            git rm -rf .
            cp -r target/site/apidocs/* .
            git add .
            git commit -m "Update Javadoc"
            git push origin gh-pages -f

      - store_test_results:
          path: target/surefire-reports/

      - codecov/upload

workflows:
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master